extends Node
class_name StreamTest
## Acceptance checks for the endless world.
##
## Two properties make streaming trustworthy, and both are invisible until they
## break:
##
##   1. A column that is unloaded and generated again is byte-identical. If it
##      is not, the world quietly rewrites itself behind the player's back.
##   2. Anything the game built survives its column being unloaded. If it does
##      not, walking away from the town demolishes it.
##
## Run with:  godot --headless --path . -- --streamtest

var world: VoxelWorld
var gen: WorldGen
var village: Village
var failures := 0


func run() -> int:
	print("\n=== endless world ===")
	_test_determinism()
	_test_features_cross_columns()
	_test_no_trimmed_features()
	_test_building_faces()
	_test_persistence()
	_test_no_holes()
	print("=== %s ===\n" % ("PASS" if failures == 0 else "%d FAILURE(S)" % failures))
	return failures


## The same column, generated twice, must come out identical — including when
## it is generated a long way from where the player started.
func _test_determinism() -> void:
	for c: Vector2i in [Vector2i(0, 0), Vector2i(7, -3), Vector2i(-412, 918),
			Vector2i(100000, -100000)]:
		var a := gen.generate_column(c.x, c.y, world.height_chunks)
		var b := gen.generate_column(c.x, c.y, world.height_chunks)
		if a.size() != b.size():
			_fail("column %v produced %d chunks then %d" % [c, a.size(), b.size()])
			continue
		var same := true
		for key: Vector3i in a:
			if not b.has(key) or (a[key] as VoxelChunk).voxels != (b[key] as VoxelChunk).voxels:
				same = false
				break
		if same:
			print("  [ok] column %v regenerates identically (%d chunks)" % [c, a.size()])
		else:
			_fail("column %v is not deterministic" % c)


## A tree that straddles a column boundary must be written the same way by both
## columns, or the seam shows a half tree.
func _test_features_cross_columns() -> void:
	var straddlers := 0
	for cz in range(-6, 7):
		for cx in range(-6, 7):
			for f: Dictionary in gen.features_near(cx, cz):
				var fx: int = f["vx"]
				var lx := fx - cx * VoxelChunk.SIZE
				var r: int = f["radius"]
				if lx - r < 0 or lx + r >= VoxelChunk.SIZE:
					straddlers += 1
	if straddlers == 0:
		_fail("no feature straddles a column boundary — the test proves nothing")
	else:
		print("  [ok] %d features straddle a column edge and are generated by both"
			% straddlers)


## The reported bug: trees with flat tops, and geometry cut off at a column
## edge. Checks every voxel each feature declares against the assembled world,
## rather than probing a guessed point — an earlier version of this test probed
## into the canopy's randomly nibbled edge and passed for the wrong reason.
func _test_no_trimmed_features() -> void:
	# Judged features come from cells -3..3, and a canopy on the edge of cell -3
	# reaches into column -4, so the installed block has to be wider than the
	# judged one or the test blames the world for its own missing ground.
	for cz in range(-5, 6):
		for cx in range(-5, 6):
			_install(cx, cz)

	var checked := 0
	var incomplete := 0
	var missing_total := 0
	var first := ""
	var seen := {}

	# Only judge features in the middle, where every column that could
	# contribute to them has been installed.
	for cz in range(-2, 3):
		for cx in range(-2, 3):
			for f: Dictionary in gen.features_near(cx, cz):
				var key := "%d,%d" % [f["vx"], f["vz"]]
				if seen.has(key):
					continue
				seen[key] = true
				checked += 1

				# Collapse to the material each position ends up with. The canopy
				# is centred over the top of the trunk and overwrites it, exactly
				# as generation does, so comparing against the raw list would
				# flag every trunk voxel under the leaves.
				var want := {}
				for e: Array in gen.feature_voxels(f):
					var v: Vector3i = e[0]
					if v.y < 0 or v.y >= world.height_chunks * VoxelChunk.SIZE:
						continue
					if not world.has_column(v.x >> 5, v.z >> 5):
						continue      # outside the installed block; not ours to judge
					want[v] = int(e[1])

				var missing := 0
				var sample: Vector3i = Vector3i.ZERO
				for v: Vector3i in want:
					if world.get_voxel(v) != int(want[v]):
						missing += 1
						sample = v
				if missing > 0:
					incomplete += 1
					missing_total += missing
					if first == "":
						first = "%s at (%d,%d): %d voxels missing, e.g. %v%s" % [
							f["type"], f["vx"], f["vz"], missing, sample,
							_diagnose(sample)]

	if checked == 0:
		_fail("no features found to check")
	elif incomplete > 0:
		_fail("%d of %d features are trimmed, %d voxels lost — %s"
			% [incomplete, checked, missing_total, first])
	else:
		print("  [ok] all %d features complete, every voxel present" % checked)


## The other half of the reported bug: a wall standing above the surrounding
## ground must have visible faces on every side. A face is only generated when
## the mesher sees non-solid next door, so this checks the world agrees that the
## air around a built wall really is air.
func _test_building_faces() -> void:
	var base_x := 3 * VoxelChunk.SIZE
	var base_z := 3 * VoxelChunk.SIZE
	var h := world.height_at(base_x + 16, base_z + 16)
	if h < 0:
		_fail("test column not installed")
		return

	# A wall tall enough to cross into the chunk above the ground.
	var top := h + 40
	for y in range(h + 1, top):
		world.set_voxel(Vector3i(base_x + 16, y, base_z + 16), VoxelTypes.BRICK)

	var exposed := 0
	var buried := 0
	for y in range(h + 2, top - 1):
		for d: Vector3i in [Vector3i(1, 0, 0), Vector3i(-1, 0, 0),
				Vector3i(0, 0, 1), Vector3i(0, 0, -1)]:
			var n := Vector3i(base_x + 16, y, base_z + 16) + d
			if world.get_voxel(n) == VoxelTypes.AIR:
				exposed += 1
			else:
				buried += 1
	if buried > 0:
		_fail("%d of %d wall faces read as buried in solid — they would be culled"
			% [buried, exposed + buried])
	else:
		print("  [ok] all %d faces of a wall above the ground read as exposed" % exposed)


## Where in the pipeline a voxel went missing: absent from generation, or
## generated but never installed.
func _diagnose(v: Vector3i) -> String:
	var cx := v.x >> 5
	var cz := v.z >> 5
	var cy := v.y >> 5
	var owning := Vector3i(cx, cy, cz)

	var fresh := gen.generate_column(cx, cz, world.height_chunks)
	var in_gen := "no chunk"
	if fresh.has(owning):
		var c: VoxelChunk = fresh[owning]
		in_gen = "present" if c.get_voxel(v.x & 31, v.y & 31, v.z & 31) != VoxelTypes.AIR 			else "AIR"
	var installed := "missing"
	if world.chunks.has(owning):
		var c2: VoxelChunk = world.chunks[owning]
		installed = "present" if c2.get_voxel(v.x & 31, v.y & 31, v.z & 31) != VoxelTypes.AIR 			else "AIR"
	return "
           chunk %v: freshly generated -> %s, in world -> %s, column loaded -> %s" % [
		owning, in_gen, installed, str(world.has_column(cx, cz))]


func _install(cx: int, cz: int) -> void:
	if world.has_column(cx, cz):
		return
	var chunks := gen.generate_column(cx, cz, world.height_chunks)
	var tile := PackedInt32Array()
	tile.resize(VoxelChunk.SIZE * VoxelChunk.SIZE)
	for lz in VoxelChunk.SIZE:
		for lx in VoxelChunk.SIZE:
			tile[lx + lz * VoxelChunk.SIZE] = gen.height_at(
				cx * VoxelChunk.SIZE + lx, cz * VoxelChunk.SIZE + lz)
	world.install_column(cx, cz, chunks, tile)


## A wall built by a worker must still be there after its column is unloaded
## and streamed back in.
func _test_persistence() -> void:
	# Somewhere well outside the pinned village, so eviction is real.
	var col := Vector2i(40, 40)
	var chunks := gen.generate_column(col.x, col.y, world.height_chunks)
	var tile := PackedInt32Array()
	tile.resize(VoxelChunk.SIZE * VoxelChunk.SIZE)
	var base_x := col.x * VoxelChunk.SIZE
	var base_z := col.y * VoxelChunk.SIZE
	for lz in VoxelChunk.SIZE:
		for lx in VoxelChunk.SIZE:
			tile[lx + lz * VoxelChunk.SIZE] = gen.height_at(base_x + lx, base_z + lz)
	world.install_column(col.x, col.y, chunks, tile)

	# Stand a small brick wall on the surface.
	var marks: Array[Vector3i] = []
	var h := world.height_at(base_x + 8, base_z + 8)
	for i in 6:
		var v := Vector3i(base_x + 8 + i, h + 1, base_z + 8)
		world.set_voxel(v, VoxelTypes.BRICK)
		marks.append(v)

	var before := 0
	for v: Vector3i in marks:
		if world.get_voxel(v) == VoxelTypes.BRICK:
			before += 1
	if before != marks.size():
		_fail("could not write the test wall at all (%d of %d)" % [before, marks.size()])
		return

	world.unload_column(col.x, col.y)
	if world.has_column(col.x, col.y):
		_fail("column still present after unload")
		return
	if world.get_voxel(marks[0]) != VoxelTypes.AIR:
		_fail("unloaded column still answers queries")

	# Stream it back in exactly as the streamer would.
	var again := gen.generate_column(col.x, col.y, world.height_chunks)
	world.install_column(col.x, col.y, again, tile)

	var after := 0
	for v: Vector3i in marks:
		if world.get_voxel(v) == VoxelTypes.BRICK:
			after += 1
	if after == marks.size():
		print("  [ok] built voxels survive an unload and reload (%d of %d)"
			% [after, marks.size()])
	else:
		_fail("only %d of %d built voxels came back" % [after, marks.size()])


## The whole point of an endless world: no gaps. Every chunk that has a face to
## show must have been given the chance to show it.
func _test_no_holes() -> void:
	for cz in range(-4, 5):
		for cx in range(-4, 5):
			_install(cx, cz)
	var holes := world.unrendered_chunks()
	# In a headless run nothing is meshed yet, so the meaningful assertion is
	# that every such chunk is at least queued rather than silently skipped.
	var skipped: Array[Vector3i] = []
	for cpos: Vector3i in holes:
		if not world._dirty.has(cpos):
			skipped.append(cpos)
	if skipped.is_empty():
		print("  [ok] every meshable chunk in a 9x9 block is queued for geometry")
	else:
		_fail("%d chunks have faces but were never queued (first %v)"
			% [skipped.size(), skipped[0]])


func _fail(msg: String) -> void:
	failures += 1
	printerr("  [FAIL] " + msg)
